# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Your awesome title
email: your-email@example.com
baseurl: "/" # the subpath of your site, e.g. /blog
description:

# Jenkins modifies this value directly with the correct url for the environment before the build
url: "https://qa.community.eupathdb.org" # the base hostname & protocol for your site, e.g. http://example.com


# Enable or disable the site search
search_enabled: true
future: true

#theme: minima

#prose:
#  siteurl: "https://devcommunity.eupathdb.org/"
prose:
  metadata:
    _posts:
      - name: "category"
        field:
          element: "multiselect"
          label: "Select Categories"
          options:
            - name: "PlasmoDB"
              value: "PlasmoDB"
            - name: "EuPathDB"
              value: "EuPathDB"


collections:
  collection_about_all: {}
  collection_resources_tools:
    output: true
    json_keys: [ output, descriptionTitle, identifier, listIconKey, listTitle ]

# this uses the list of projects in _data/projects.yml to iterate and build all the embedded help pages
# each of these pages will be build using the _layouts/help.html template.  

page_gen-dirs: false
page_gen:
  - data: 'projects'
    template: 'help'
    name: 'name'
    dir: 'aboutall'
  - data: 'general'
    template: 'help'
    name: 'name'
    dir: 'aboutall'

plugins:
  - jekyll-seo-tag
  - jekyll-feed

feed:
  categories:
    - AmoebaDB
    - ClinEpiDB
    - CryptoDB
    - EuPathFB
    - FungiDB
    - GiardiaDB
    - HostDB
    - MicrobiomeDB
    - MicrosporidiaDB
    - PiroplasmaDB
    - PlasmoDB
    - SchistoDB
    - ToxoDB
    - TrichDB
    - TriTrypDB
    - VectorBase
